name: Run

on:
  schedule:
    - cron: '40 2 * * *' # 确保这行没有被注释掉，并且 '40 2 * * *' 是你最后一次修改的结果
  workflow_dispatch: # 可以保留手动触发，不影响自动触发


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 选择所需的 Python 版本

    - name: Install dependencies
      run: pip install -r requirements.txt  # 根据你的需求修改 requirements.txt 文件路径

    - name: Run
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ACCOUNTS_AND_PASSWORDS: ${{ secrets.ACCOUNTS_AND_PASSWORDS }}
      run: python steps.py
